# Generated by Django 5.2 on 2025-05-03 06:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestResponse',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_body', models.JSONField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_request_response',
                'indexes': [models.Index(fields=['request_id'], name='api_request_request_57c91b_idx'), models.Index(fields=['created_at'], name='api_request_created_fb00e0_idx')],
            },
        ),
    ]
