# Generated by Django 5.2 on 2025-05-03 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('event', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'webhook_data',
                'indexes': [models.Index(fields=['request_id'], name='webhook_dat_request_cde20d_idx'), models.Index(fields=['event'], name='webhook_dat_event_e3cc09_idx'), models.Index(fields=['status'], name='webhook_dat_status_bc3937_idx'), models.Index(fields=['received_at'], name='webhook_dat_receive_81dc73_idx')],
            },
        ),
    ]
