# Generated by Django 4.2.20 on 2025-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webset', '0002_webhookdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestresponse',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apirequestresponse',
            name='request_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apirequestresponse',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
