# Generated by Django 4.2.20 on 2025-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webset', '0003_apirequestresponse_request_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdata',
            name='request_id',
            field=models.UUIDField(),
        ),
    ]
