# Exa.ai API Constants
EXA_API_BASE_URL = "https://api.exa.ai"
EXA_WEBSETS_ENRICHMENTS_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}/enrichments"
EXA_WEBSETS_UPDATE_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}"
EXA_WEBSETS_LIST_URL = f"{EXA_API_BASE_URL}/websets/v0/websets"
EXA_WEBSETS_ITEMS_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}/items/{{item_id}}"
EXA_WEBSETS_ITEMS_LIST_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}/items"
EXA_WEBSETS_ENRICHMENTS_CREATE_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}/enrichments"
EXA_WEBSETS_ENRICHMENTS_GET_URL = f"{EXA_API_BASE_URL}/websets/v0/websets/{{webset_id}}/enrichments/{{enrichment_id}}"
EXA_WEBSETS_EVENTS_GET_URL = f"{EXA_API_BASE_URL}/websets/v0/events/{{event_id}}"
EXA_WEBHOOKS_GET_URL = f"{EXA_API_BASE_URL}/websets/v0/webhooks/{{webhook_id}}"
EXA_WEBSETS_WEBHOOKS_CREATE_URL = f"{EXA_API_BASE_URL}/websets/v0/webhooks"
EXA_WEBSETS_WEBHOOKS_RECEIVE_URL = f"{EXA_API_BASE_URL}/websets/v0/webhooks/receive"
EXA_WEBSETS_WEBHOOKS_UPDATE_URL = f"{EXA_API_BASE_URL}/websets/v0/webhooks/{{webhook_id}}"